import { Event, Customer, Organizer, Vendor } from "./accsEventsCollections";

export const mockEvents: Event[] = [
  {
    eventId: "event1",
    eventName: "Tech Conference 2025",
    eventDescription: "A conference about the latest in technology.",
    organizerId: "org1",
    vendorsIds: ["vendor1", "vendor2"],
    eventDate: new Date("2025-06-15"),
    location: {
      venueName: "Grand Hall",
      address: "123 Main St",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
    },
    categories: ["Technology", "Innovation"],
    attendeeIds: ["cust1", "cust2"],
    created_at: new Date(),
  },
  {
    eventId: "event2",
    eventName: "Music Festival 2025",
    eventDescription: "An outdoor festival featuring top artists.",
    organizerId: "org2",
    vendorsIds: ["vendor3"],
    eventDate: new Date("2025-07-20"),
    location: {
      venueName: "Sunset Park",
      address: "456 Sunset Blvd",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
    },
    categories: ["Music", "Festival"],
    attendeeIds: ["cust3", "cust4"],
    created_at: new Date(),
  },
  {
    eventId: "event3",
    eventName: "Startup Pitch Night",
    eventDescription: "A night where startups pitch to investors.",
    organizerId: "org3",
    vendorsIds: ["vendor1"],
    eventDate: new Date("2025-08-10"),
    location: {
      venueName: "Innovation Hub",
      address: "789 Tech St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    categories: ["Business", "Investment"],
    attendeeIds: ["cust5", "cust6"],
    created_at: new Date(),
  },
  {
    eventId: "event4",
    eventName: "Food Expo 2025",
    eventDescription: "Showcasing the best culinary experiences.",
    organizerId: "org4",
    vendorsIds: ["vendor4", "vendor5"],
    eventDate: new Date("2025-09-05"),
    location: {
      venueName: "Expo Center",
      address: "101 Food St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    categories: ["Food", "Exhibition"],
    attendeeIds: ["cust7", "cust8"],
    created_at: new Date(),
  },
  {
    eventId: "event5",
    eventName: "Health & Wellness Fair",
    eventDescription: "A fair promoting health and wellness.",
    organizerId: "org5",
    vendorsIds: ["vendor6"],
    eventDate: new Date("2025-10-10"),
    location: {
      venueName: "Wellness Center",
      address: "202 Care St",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    categories: ["Health", "Wellness"],
    attendeeIds: ["cust9", "cust10"],
    created_at: new Date(),
  },
  {
    eventId: "event6",
    eventName: "Gaming Tournament",
    eventDescription: "A competitive gaming tournament.",
    organizerId: "org6",
    vendorsIds: ["vendor2"],
    eventDate: new Date("2025-11-20"),
    location: {
      venueName: "Esports Arena",
      address: "303 Game St",
      city: "Las Vegas",
      state: "NV",
      zipCode: "89109",
    },
    categories: ["Gaming", "Competition"],
    attendeeIds: ["cust11", "cust12"],
    created_at: new Date(),
  },
];

export const mockCustomers: Customer[] = [
  {
    customerId: "cust1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNum: "123-456-7890",
    address: {
      address: "456 Elm St",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
    },
    registeredEvents: ["event1", "event3"],
    favoriteEvents: ["event5"],
    created_at: new Date(),
  },
  {
    customerId: "cust2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNum: "987-654-3210",
    address: {
      address: "789 Oak St",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
    },
    registeredEvents: ["event2"],
    favoriteEvents: ["event6"],
    created_at: new Date(),
  },
];

export const mockOrganizers: Organizer[] = [
  {
    organizerId: 1,
    organizationName: "Tech Innovators",
    contactPerson: "Alice Johnson",
    image: "",
    email: "alice@techinnovators.com",
    phoneNum: "123-999-4567",
    address: {
      address: "123 Silicon St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
    },
    price: 5000,
    eventsOrganized: ["Tech Expo", "AI Summit"],
    website: "https://techinnovators.com",
    socialMedia: { facebook: "facebook.com/techinnovators" },
    rating: 4.8,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-01-01"),
      endDate: new Date("2025-12-31"),
    },
    timeSlot: ["10:00 AM - 12:00 PM", "2:00 PM - 4:00 PM"],
    certifications: ["Certified Tech Organizer"],
    description: "",
    industry: "",
    phone: "",
  },
  {
    organizerId: 2,
    organizationName: "Event Masters",
    contactPerson: "Bob Williams",
    image: "",
    email: "bob@eventmasters.com",
    phoneNum: "987-654-3210",
    address: {
      address: "456 Broadway Ave",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    price: 7500,
    eventsOrganized: ["Corporate Meetings", "Weddings"],
    website: "https://eventmasters.com",
    socialMedia: { twitter: "twitter.com/eventmasters" },
    rating: 4.5,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-02-15"),
      endDate: new Date("2025-11-30"),
    },
    timeSlot: ["9:00 AM - 11:00 AM", "3:00 PM - 5:00 PM"],
    certifications: ["Event Planning Expert", "Wedding Specialist"],
    description: "",
    industry: "",
    phone: "",
  },
  {
    organizerId: 3,
    organizationName: "Green Earth Events",
    contactPerson: "Emma Green",
    image: "",
    email: "emma@greenearth.com",
    phoneNum: "555-123-4567",
    address: {
      address: "789 Eco Lane",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    price: 6000,
    eventsOrganized: ["Eco Conferences", "Sustainable Living Workshops"],
    website: "https://greenearth.com",
    socialMedia: { instagram: "instagram.com/greenearth" },
    rating: 4.9,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-03-10"),
      endDate: new Date("2025-09-20"),
    },
    timeSlot: ["8:00 AM - 10:00 AM", "1:00 PM - 3:00 PM"],
    certifications: ["Eco-Friendly Events Certified"],
    description: "",
    industry: "",
    phone: "",
  },
  {
    organizerId: 4,
    organizationName: "Luxury Gatherings",
    contactPerson: "David Smith",
    image: "",
    email: "david@luxurygatherings.com",
    phoneNum: "222-888-7777",
    address: {
      address: "101 Royal Blvd",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90015",
    },
    price: 12000,
    eventsOrganized: ["High-End Galas", "Celebrity Parties"],
    website: "https://luxurygatherings.com",
    socialMedia: {
      facebook: "facebook.com/luxurygatherings",
      instagram: "instagram.com/luxurygatherings",
    },
    rating: 4.7,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-04-05"),
      endDate: new Date("2025-10-31"),
    },
    timeSlot: ["7:00 PM - 11:00 PM"],
    certifications: ["Luxury Event Specialist"],
    description: "",
    industry: "",
    phone: "",
  },
  {
    organizerId: 5,
    organizationName: "Sports Event Pros",
    contactPerson: "Michael Jordan",
    image: "",
    email: "michael@sportseventpros.com",
    phoneNum: "333-555-6666",
    address: {
      address: "500 Stadium Rd",
      city: "Chicago",
      state: "IL",
      zipCode: "60616",
    },
    price: 8500,
    eventsOrganized: ["Basketball Tournaments", "Marathons"],
    website: "https://sportseventpros.com",
    socialMedia: { twitter: "twitter.com/sportseventpros" },
    rating: 4.6,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-06-01"),
      endDate: new Date("2025-12-15"),
    },
    timeSlot: ["6:00 AM - 10:00 AM", "4:00 PM - 8:00 PM"],
    certifications: ["Certified Sports Event Planner"],
    description: "",
    industry: "",
    phone: "",
  },
  {
    organizerId: 6,
    organizationName: "Cultural Festivals Inc.",
    contactPerson: "Sophia Martinez",
    image: "",
    email: "sophia@culturalfestivals.com",
    phoneNum: "777-444-8888",
    address: {
      address: "25 Heritage St",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    price: 5500,
    eventsOrganized: ["Music Festivals", "Cultural Parades"],
    website: "https://culturalfestivals.com",
    socialMedia: {
      facebook: "facebook.com/culturalfestivals",
      twitter: "twitter.com/culturalfestivals",
    },
    rating: 4.8,
    created_at: new Date(),
    availability: {
      startDate: new Date("2025-05-20"),
      endDate: new Date("2025-11-15"),
    },
    timeSlot: ["5:00 PM - 9:00 PM"],
    certifications: ["Cultural Event Organizer"],
    description: "",
    industry: "",
    phone: "",
  },
];

export const mockVendors: Vendor[] = [
  {
    vendorId: "vendor1",
    vendorName: "Gourmet Bites",
    servicesProvided: ["Catering", "Food Delivery"],
    contactPerson: "Mark Brown",
    email: "mark@gourmetbites.com",
    phoneNum: "555-234-5678",
    address: {
      address: "456 Food St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    eventsParticipated: ["event1", "event5"],
    ratings: 4.9,
    availability: {
      startDate: new Date("2025-02-01"),
      endDate: new Date("2025-12-01"),
    },
    created_at: new Date(),
    certifications: ["Health & Safety", "Culinary Excellence"],
  },
];
